// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmecwbISj-nRGPyY3u__yWZp45xg7jktA',
    appId: '1:137054042464:web:1f9bf2c278491ebd9e8605',
    messagingSenderId: '137054042464',
    projectId: 'voice-cook-ea47c',
    authDomain: 'voice-cook-ea47c.firebaseapp.com',
    storageBucket: 'voice-cook-ea47c.firebasestorage.app',
    measurementId: 'G-ZGRXPES27P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHHWpXHOEVQlem6J5Ng9baHoQPXteKZbU',
    appId: '1:137054042464:android:8e6d74f4c13984ca9e8605',
    messagingSenderId: '137054042464',
    projectId: 'voice-cook-ea47c',
    storageBucket: 'voice-cook-ea47c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYWS_CNsWcj3T_edoxHL_-XjK1x-9qHJo',
    appId: '1:137054042464:ios:53bc60444de28f489e8605',
    messagingSenderId: '137054042464',
    projectId: 'voice-cook-ea47c',
    storageBucket: 'voice-cook-ea47c.firebasestorage.app',
    iosBundleId: 'com.example.voicecook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYWS_CNsWcj3T_edoxHL_-XjK1x-9qHJo',
    appId: '1:137054042464:ios:53bc60444de28f489e8605',
    messagingSenderId: '137054042464',
    projectId: 'voice-cook-ea47c',
    storageBucket: 'voice-cook-ea47c.firebasestorage.app',
    iosBundleId: 'com.example.voicecook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmecwbISj-nRGPyY3u__yWZp45xg7jktA',
    appId: '1:137054042464:web:952c71fd635b4b939e8605',
    messagingSenderId: '137054042464',
    projectId: 'voice-cook-ea47c',
    authDomain: 'voice-cook-ea47c.firebaseapp.com',
    storageBucket: 'voice-cook-ea47c.firebasestorage.app',
    measurementId: 'G-0MYZRX3JBD',
  );
}
